// Clientbound
mod clientbound_plugin_message;
mod disconnect;
mod clientbound_finish_configuration;
mod clientbound_keep_alive;
mod ping;
mod registry_data;
mod remove_resource_pack;
mod add_resource_pack;
mod feature_flags;
mod update_tags;
// Serverbound
mod client_information;
mod serverbound_plugin_message;
mod serverbound_finish_configuration;
mod serverbount_keep_alive;
mod pong;
mod resource_pack_response;
