[package]
name = "slot_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
nbt_lib = { path = "../nbt_lib" }
datatypes = { path = "../datatypes" }
binary_utils = { path = "../binary_utils" }
tokio = { version = "1.37.0", features = ["io-util"] }
