[package]
name = "datatypes"
version = "0.1.0"
edition = "2021"

[dependencies]
binary_utils = { path = "../binary_utils" }
serde = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.36.0", features = ["io-util"] }
